### ISSUE TITLE
Clicking the Options netherstar duplicates it

### ISSUE THREAD

**Issue by sandro628** [Drawethree/PRO-BuildBattle#1]
**Describe the bug**
Title.

**To Reproduce**
Go into your inventory during a game and click on the netherstar, it's duplicated.

**Expected behavior**
The event should be cancelled without the duplication of the netherstar.

**Screenshots**
http://prnt.sc/oxxp6c

**Server Information (please complete the following information):**
 - Java 8
 - Paper 1.13.2

**Additional context**
N/A

**Comment by sandro628** [comment]
Seems to have fixed itself after a restart.

**Comment by Drawethree** [comment]
Thank you for reporting a bug! I will investigate it when I am back from
vacation.

Dňa ut 27. 8. 2019 o 7:21 Aello Development <notifications@github.com>
napísala(a):
